# Generated by Django 2.2.1 on 2019-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquery',
            fields=[
                ('inq_id', models.AutoField(primary_key=True, serialize=False)),
                ('inq_nam', models.CharField(max_length=100)),
                ('inq_mail', models.CharField(max_length=50)),
                ('inq_mono', models.CharField(max_length=15)),
                ('inq_subj', models.CharField(max_length=250)),
                ('inq_det', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
