# Generated by Django 2.2.1 on 2019-06-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cor_id', models.AutoField(primary_key=True, serialize=False)),
                ('cor_cat', models.CharField(max_length=20)),
                ('cor_nam', models.CharField(max_length=50)),
                ('cor_ful_form', models.CharField(max_length=100)),
                ('cor_dur', models.CharField(max_length=50)),
                ('cor_pak', models.CharField(default='', max_length=10)),
                ('cor_detail', models.CharField(max_length=250)),
                ('cor_syllabus', models.ImageField(default='', upload_to='cit/images')),
            ],
        ),
    ]
