# Generated by Django 2.2.1 on 2019-06-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_registration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_frm_no', models.CharField(max_length=10)),
                ('reg_nam', models.CharField(max_length=50)),
                ('reg_gen', models.CharField(max_length=50)),
                ('reg_fat_nam', models.CharField(max_length=50)),
                ('reg_mot_nam', models.CharField(max_length=50)),
                ('reg_dob', models.DateField()),
                ('reg_location', models.CharField(max_length=150)),
                ('reg_mono', models.CharField(max_length=15)),
                ('reg_fat_mono', models.CharField(max_length=15)),
                ('reg_cat', models.CharField(max_length=50)),
                ('reg_cor', models.CharField(max_length=50)),
                ('reg_psd_cls', models.CharField(max_length=50)),
                ('reg_psd_year', models.IntegerField()),
                ('reg_board', models.CharField(max_length=50)),
                ('reg_gred', models.CharField(max_length=50)),
                ('reg_img', models.ImageField(upload_to='cit/images')),
                ('reg_det', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
