# Generated by Django 2.2.1 on 2019-06-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0004_std_exm_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_exm_marks',
            name='exm_std_img',
            field=models.CharField(default='', max_length=50),
        ),
    ]
