# Generated by Django 2.2.1 on 2019-06-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0005_std_exm_marks_exm_std_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_std_id', models.CharField(max_length=10)),
                ('fee_std_nam', models.CharField(max_length=50)),
                ('fee_fat_nam', models.CharField(max_length=50)),
                ('fee_cors', models.CharField(max_length=50)),
                ('fee_location', models.CharField(max_length=150)),
                ('fee_std_img', models.CharField(max_length=50)),
                ('jan_fee', models.IntegerField(default=0)),
                ('jan_fee_det', models.DateField(default='')),
                ('feb_fee', models.IntegerField(default=0)),
                ('feb_fee_det', models.DateField(default='')),
                ('mar_fee', models.IntegerField(default=0)),
                ('mar_fee_det', models.DateField(default='')),
                ('apr_fee', models.IntegerField(default=0)),
                ('apr_fee_det', models.DateField(default='')),
                ('may_fee', models.IntegerField(default=0)),
                ('may_fee_det', models.DateField(default='')),
                ('jun_fee', models.IntegerField(default=0)),
                ('jun_fee_det', models.DateField(default='')),
                ('jul_fee', models.IntegerField(default=0)),
                ('jul_fee_det', models.DateField(default='')),
                ('aug_fee', models.IntegerField(default=0)),
                ('aug_fee_det', models.DateField(default='')),
                ('sep_fee', models.IntegerField(default=0)),
                ('sep_fee_det', models.DateField(default='')),
                ('oct_fee', models.IntegerField(default=0)),
                ('oct_fee_det', models.DateField(default='')),
                ('nov_fee', models.IntegerField(default=0)),
                ('nov_fee_det', models.DateField(default='')),
                ('dec_fee', models.IntegerField(default=0)),
                ('dec_fee_det', models.DateField(default='')),
            ],
        ),
    ]
