# Generated by Django 2.2.1 on 2019-06-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0006_std_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_fee',
            name='apr_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='aug_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='dec_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='feb_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='jan_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='jul_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='jun_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='mar_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='may_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='nov_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='oct_fee_det',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='std_fee',
            name='sep_fee_det',
            field=models.DateField(default='', null=True),
        ),
    ]
