# Generated by Django 2.2.1 on 2019-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0007_auto_20190629_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_fee',
            name='due_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='std_fee',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
    ]
