from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('usr_reg', views.usr_reg, name='usr_reg'),
    path('usr_inq', views.usr_inq, name='usr_inq'),
    path('usr_login', views.usr_login, name='usr_login'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('admin', views.admin, name='admin'),
    path('enqu', views.enqu, name='enqu'),
    path('cou_rse', views.cou_rse, name='cou_rse'),
    path('add_course', views.add_course, name='add_course'),
    path('update_cors/<int:cors_id>', views.update_cors, name='update_cors'),
    path('del_cors/<int:cors_id>', views.del_cors, name='del_cors'),
    path('std_reg', views.std_reg, name='std_reg'),
    path('add_std', views.add_std, name='add_std'),
    path('std_list', views.std_list, name='std_list'),
    path('std_view/<int:std_id>', views.std_view, name='std_view'),
    path('update_std/<int:std_id>', views.update_std, name='update_std'),
    path('del_std/<int:std_id>', views.del_std, name='del_std'),
    path('add_marks', views.add_marks, name='add_marks'),
    path('marks', views.marks, name='marks'),
    path('result_list', views.result_list, name='result_list'),
    path('result_view/<int:exm_id>', views.result_view, name='result_view'),
    path('update_marks/<int:exm_id>', views.update_marks, name='update_marks'),
    path('view_cretificate', views.view_cretificate, name='view_cretificate'),
    path('add_fee', views.add_fee, name='add_fee'),
    path('fee', views.fee, name='fee'),
    path('fee_list', views.fee_list, name='fee_list'),
    path('fee_view/<int:fee_id>', views.fee_view, name='fee_view'),
    path('usr_logout', views.usr_logout, name='usr_logout'),
    path('check', views.check, name='check'),
    path('check2', views.check2, name='check2'),
]